# Generated by Django 4.0.7 on 2022-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='export',
            name='type',
            field=models.CharField(choices=[('ratings', 'Ratings'), ('movies', 'Movies')], default='ratings', max_length=20),
        ),
    ]
