# Generated by Django 4.0.7 on 2022-09-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
