# Generated by Django 4.0.7 on 2022-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='idx',
            field=models.IntegerField(blank=True, help_text='Position IDs for ML', null=True),
        ),
    ]
